### ISSUE TITLE
Conflict with OPT Space Planes or mods which it is dependent on

### ISSUE THREAD

**Issue by Deluxeinator** [NathanKell/ModularFuelSystem#176]
Hello, i have a weird bug when i have both OPT and Real Fuels installed with their dependent mods. What happens is that when i bring an OPT part out to either the launchpad or airstrip the part becomes "fixed" to a point in space, the part can freely rotate around the point but not move away from it.

These are the mods that i run and all of them are installed by CKAN
> CommunityResourcePack
> Firespitter
> OPT
> RealFuels
> RealFuels-Stockalike
> RSS-Textures
> SolverEngines

**Comment by blowfishpro** [comment]
Could you upload your KSP.log?  Hard to see what's going on without that...

**Comment by Deluxeinator** [comment]
whoops, forgot to post those,

[output_log.txt](https://drive.google.com/open?id=0B79or6UNN5FIc2xrNTJUMEpySlU)
[ksp.log](https://drive.google.com/open?id=0B79or6UNN5FIVllWYVR1N0FJMkE)

**Comment by Deluxeinator** [comment]
also i tried running the game without RealFuels, RealFuels-Stockalike and the OPT parts behaved normally

**Comment by blowfishpro** [comment]
Figured it out.  OPT has some rather messy and broken patches for RF.  If you look in `OPT/mm_config/OPT_RF.cfg` and `OPT/mm_config/OPT_MFT.cfg` you might see that every part exists in both, but that both are `NEEDS[RealFuels` (whereas the MFT one should only be for MFT).

For now, deleting `OPT/mm_config/OPT_MFT.cfg` should fix the problem, but I'm not sure the RF patches in OPT are even remotely up to date.  The volume in the RF patches should be about 5 times what it is in the MFT version, which it isn't, so the volumes might be wrong.  Parts like cockpits and cargo bays probably need additional configuration too, since their mass should be more than that of just the tank.  Regardless, you should probably report the problem with the patches in the OPT thread.

Feel free to re-open this issue if you discover anything more is required on the RF side.
