### ISSUE TITLE
Resource cost is applied twice

### ISSUE THREAD

**Issue by pellinor0** [NathanKell/ModularFuelSystem#178]
stock wet cost becomes dry cost when MFT is installed. 

Example Rockomax X200-16: 
stock: dry=816, wet=1550
with MFT: dry=1550, wet=2284

**Comment by Starwaster** [comment]
Confirmed. And the discrepancy is by exactly the cost of the resources. (in the example given by @pellinor0  the discrepancy corresponds to the default LF-O ratio but it could actually vary depending on specific resources assigned by the player). For the big 3.75m stock tanks this is a big hit for the player: A 13000 fund tank balloons to 19610.

Probably an issue with ModuleFuelTanks.GetModuleCost() which I see two things going wrong in:

1. It's returning a set amount instead of an offset (GetModuleCost calculates the cost but returns that value which is then seen by stock KSP as an amount to increase the part cost by)
2. Only resource costs are getting calculated here. The code may support dry tank cost calculation but that needs a baseCost to be configured. (Applies to MFS, not to RF which _does_ handle dry costs for tanks in its configs)
