### ISSUE TITLE
MLI Slider Limits

### ISSUE THREAD

**Issue by pap1723** [NathanKell/ModularFuelSystem#216]
Hey @starwaster,
As I mentioned in Discord, we are looking to control the amount of MLI that can be added to tanks.

Initislly the thought was that we could gate it via tech, but an alternative option would be to set it in the tank configs like utilization is setup now. So the config can be minMLI = 0 and maxMLI = 25.

Setting it in the config file might actually be the best option. However, the tech idea is that at the beginning, you can have the slider have a max Value that can be unlocked through tech like your Tech Levels system. 

https://github.com/NathanKell/ModularFuelSystem/blob/master/Source/Tanks/ModuleFuelTanksRF.cs#L22

That's the code I saw that is affected in the front end GUI. 

Let me know if I wasn't clear about anything. Thanks! 
Pap

**Comment by Bornholio** [comment]
Clear as mud, :)  how about TL config for mass per layer, or MLI limits percentage utilization

**Comment by NathanKell** [comment]
I tend to think varying insulation weight makes more sense?

Sent by my thumbs, slowly.

**Comment by NathanKell** [comment]
Where is MLI insulation weight set? And where is the max layers possible to select set?

**Comment by Starwaster** [comment]
Insulation mass is currently hard coded in ModuleFuelTanksRF.CalculateMassRF() as 0.00015 * m2 * layers

maximum layers is maxValue for  _numberOfAddedMLILayers (UI_FloatRange) so it's likewise hard coded, but it should be fairly trivial to instead store those values in a field that can be modified via PartStatsUpgradeModule

**Comment by NathanKell** [comment]
Coolz. I would think it would be even easier to expose the mass, tbh. Just add a KSPField for it, and PartStatsUpgrade will handle the rest.

**Comment by Starwaster** [comment]
Need to figure what the default maxMLILayers value should be keeping in mind stock + RealFuels because not _all_ users are RO. I have it at 10 right now which is (probably?) a good starting point for RO. For stock, maybe bump it up a bit since there's maybe 5 appropriate tech categories to upgrade in.

Not sure how many tech categories there actually are in the RP0 / RP1 tree to play with, or maybe create a new set for this?

At any rate, it's KSPField so it can be overridden in the actual MODULE regardless of what value is hard coded in the class.

Cost hasn't been mentioned; it too is currently hard coded from a value determined both material value and labor. (determined by browsing literature from various companies selling Kapton and Mylar sheeting). It should probably be exposed the way we'll be doing for mass. Probably shouldn't be linear either, which it currently is. ($ * m2 * layers)

**Comment by Starwaster** [comment]
As currently implemented, maxMLILayers ONLY applies to the number of layers that can be added by the player via the MLI Layers slider. 

If the tank type has MLI configured then those layers are added to whatever the player adds. Two tank types currently come with 10 layers of MLI _which are not counted against the layer limit._ If this is not desirable let me know.

**Comment by pap1723** [comment]
Thanks @Starwaster! Can this be back ported to 1.3.1 and 1.4.5?

**Comment by Starwaster** [comment]
Yeah. Should I also (temporarily) undo that engine status change that's screwing up MJ's ability to do ullage control?

**Comment by NathanKell** [comment]
@lamont-granquist is that needed still or is MJ updated?

**Comment by lamont-granquist** [comment]
MJ isn't updated, but I don't think you should revert it.

I'll try to take a look at fixing it tomorrow.

**Comment by Starwaster** [comment]
Pushed the commits for this to the repository. Will look at doing releases and backporting... soon.

**Comment by Starwaster** [comment]
Closed; layers, layer mass and layer cost added as reconfigurable.
