### ISSUE TITLE
Cross reference: Log spam and very low fps in VAB/SPH when RF UI is open (FAR)

### ISSUE THREAD

**Issue by Gordon-Dry** [NathanKell/ModularFuelSystem#221]
see
https://github.com/dkavolis/Ferram-Aerospace-Research/issues/67

**Comment by Gordon-Dry** [comment]
@yump Thank you for appreciating this issue although it was just closed.

**Comment by Starwaster** [comment]
FYI this is closed because links to other mod's issues are not an acceptable means of bug reporting. This sort of thing has used up too much of my time in the past. Sorry but this isn't how you get problems solved

The aforementioned pull request is the best way. Granted that not everyone is a programmer but even pointing my attention to the editor event firing every graphics frame would have been enough. Do you see the difference? **I am not trying to bust your chops** but I'm done with trying to trace issues that might or might not exist in mod #1 by scouring mod#2's bug reports and most especially if the logs only show errors in the other mod.
