### ISSUE TITLE
RealFuels 12.8.0 for KSP 1.6.x huge delays and lagging

### ISSUE THREAD

**Issue by Gordon-Dry** [NathanKell/ModularFuelSystem#231]
As already mentioned in the RO Discord, now here again:

Loading a vessel into VAB:
delays on each instance of 
`DragCubeSystem: Rendering procedural drag for  ... `
followed by FAR updating voxels and TU saving color presets.

Right-clicking an engine and then clicking the "Engine" button:
(huge delay of ~10s - then the UI came up)
same as above;
delays on each instance of 
`DragCubeSystem: Rendering procedural drag for  ... `
followed by FAR updating voxels and TU saving color presets.

And closing the "Engine" UI also got a huge delay, with one difference;
delays on each instance of 
`DragCubeSystem: Rendering procedural drag for  ... `
followed by FAR updating voxels (but this time not TU saving color presets).

"Tank UI" reacts quick, though, but very slow when changing a value and pressing "Update":
delays on each instance of 
`DragCubeSystem: Rendering procedural drag for  ... `
followed by FAR updating voxels and TU saving color presets.

And:
I created a copy of the craft file and after loading was done I saved it and then compared the files ...
Several tank's contents were altered.
This could be intentional, because of the underlying changes.
But I'm not sure, so I mention it here as well.
Original: Raketa-Cam-7.craft
After loading with RealFuels 12.8.0 and saving again: Raketa-Cam-7-1.craft

Because I'm not deep inside this stuff I cannot say if this is perhaps a SolverEngines issue or a RealFuels issue or both.

My actual log and stuff (not the same as in the Discord post):
https://www.dropbox.com/s/o601kvkme9ktnsr/output_log.txt%20and%20stuff%202019-08-30-02.zip?dl=1

**Comment by Starwaster** [comment]
Explain what you mean by 'several tank's contents were altered' I don't understand

**Comment by Gordon-Dry** [comment]
For example, the avionics of the top stage got 50 units of SoundingPayload.
After loading the vessel (after updating to RF 12.8.0) it got ~20.

All other tank contents have been the same (well, nearly, you know KSP and the floating point numbers).

This is a screenshot of a file comparision, only showing the lines that differ:
![Screen-2019-08-31_00-37-51](https://user-images.githubusercontent.com/29145213/64054523-a9b8e100-cb87-11e9-9899-852048b2472b.jpg)

**Comment by Starwaster** [comment]
Nothing you're describing could be SolverEngine related. No point in implicating that.
As for the Raketa craft, how was this copying done? You mean you loaded it and then saved it and those changes happened without you touching any RF menus or otherwise editing the craft? 

What is the craft's origin? 

Regarding the delay, from your description it sounds like that is happening on procedural parts when RF has to calculate its surface area. If so then it's a new change different from any previous lag you might have experienced. And I probably cannot do anything about it because of what I'm having to do to get consistent surface area calculations on the part between editor and flight mode. 

It _should_ only happen for procedural parts (SSTU, Procedural Parts, ROTanks and B9 Procedural Wings) since it's specifically looking for part resizing modules from those mods. And it has to rerender EVERY time a change is reported because the code doesn't necessarily know what the change was. 

Also can't do anything about FAR voxels doing their thing. Probably happens because if the drag cube rerendering but I can't do anything about that without regressing back to a bug that was fixed regarding tank mass on procedural parts.

**Comment by Gordon-Dry** [comment]
The craft was created two days ago.
Yesterday, after updating RealFuels to 12.8.0, I loaded in into VAB and saved it immediately.
The comparision is between the original version and the saved version.

When ever there was a lag before the update it was so ridiculously small and un-recognizable (in the miliseconds) that I can't tell it a lag for real.
Last version was ofc the RealFuels.dll shipped with ROTanks:
https://github.com/KSP-RO/ROTanks/commit/55cfd1594240f06c1b9c4512fa40476beb9a2ba6

**Comment by Gordon-Dry** [comment]
Copy of I wrote in Discord recently:

I just boot up KSP after reverting RF to 12.7.4 (and the ROTanks' RealFuels.dll and RP-1 NQB) - but not reverting SolverEngines. Let's see what happens then in VAB.

Smooth.

So, the same stuff is done:
- updating FAR vosels
- saving TU color presets
But not the drag cube stuff.

With 12.8.0 all of them (FAR voxels, TU color presets and drag cube stuff) had delays - but I guess that the drag cube part is the most delaying/lagging part because RF 12.7.4 does not have it.

So the most obvious change from 12.7.4 to 12.8.0 is the already mentioned-above
`DragCubeSystem: Rendering procedural drag for  ...`
with a multi-seconds lag
... which happens after each click on "Engine" button or "Update" inside the tank UI.
And ofc when the vessel is loaded into VAB for all parts that contain an RF tank.
Which sums up to a really huge delay of up to 30s when loading a craft into VAB.
^(the craft is already loaded, the whole KSP UI is unresponsive for that amount of time)

**Comment by Starwaster** [comment]
Issue should be resolved at this point by new update.
