### ISSUE TITLE
Warp-burn Plugin Intergration issue

### ISSUE THREAD

**Issue by Kerbinator-CN** [NathanKell/ModularFuelSystem#235]
I`m currently using DSEV,RF and Principia,full RO kit(RO squad configs was deleted) and KSP 1.6.1.I haven`t used any DSEV engines yet,however I found that DSEV applied its warp plugin to my NTR(despite being completely useless due to Principia).And then I found that once NTR is installed to my ship,the G-Force meter went to zero immediately and ullage system become immediately abnormal after S1 Raptor seperation:The engine fail 5s after ignition (when propellant stability was 92%,showing vapor in feed lines)and then it drop quickly(about ~30s) to zero(Unstable propellant)
Here are my debug thread (which cost A LOT OF TIME as a student):
1.remove RFTestFlight dll:useless
2.modifying RF stockalike squad(without ullage removel):FAILED
3.used both RF122-built in cfg and RF161 stockalike cfg,both FAILED.
So pls support warp plugin's system since I still want to use RO ion engine for my manned Mercury (MESSENGER-style) mission.I also report another issue that Principia completely multilate the warp plugin.
Hoping to see a happy collaboration between you (and the RO team) with Principia team!
Your work should be a proper resource draining system fou warp plugin.

**Comment by Starwaster** [comment]
The details of this issue (as presented) are confusing. 

What exactly are you saying that Principia's role in this issue is? I don't understand. You say the warp plugin is 'completely useless due to Principia' which makes it sound like there's an issue between the two before Real Fuels is even considered. If that's the case, isn't this really just an issue between Principia and Warp Burn? Why not just remove Warp Burn since it is 'completely useless'?

Given that both Real Fuels and Principia are used by a lot of RO players and given that I spend a lot of time in the RO development channels and nobody has raised Principia issues to me there, I think you should retest _without_ Principia. If you still have a problem then I'll look into it.
