### ISSUE TITLE
Rated Burn Time display bug

### ISSUE THREAD

**Issue by lpgagnon** [NathanKell/ModularFuelSystem#311]
Most xlr11 configs have a rated continuous time; the xlr35 config doesn't. The realfuels info window shows the rated time in 3 places; 2 get it right, showing only the rated time; one gets confused into showing the continous time of other configs

<img width="491" alt="Screenshot 2023-05-14 at 18 59 22" src="https://github.com/NathanKell/ModularFuelSystem/assets/5061230/415484c1-a4c7-4d8c-8eaf-8824ebb6553b">

The wrong one appears to be coming from https://github.com/NathanKell/ModularFuelSystem/blob/8ace999f82198eb61bafab27dc15f5dce9f3291d/Source/Engines/ModuleEnginesRF.cs#L910 

not immediately seeing why it gets it wrong.

easy fix, just remove it? it's weird that the window has two 'rated time' lines

**Comment by NathanKell** [comment]
This is actually a bug in the config. If one CONFIG specifies a value, all CONFIGs have to specify their version of the value. RF is behaving properly here I believe, because the way RF works is additively loading a CONFIG on top of the existing PM's members, not starting fresh (how could it?), so once a value is changed by loading one CONFIG, it's changed until it's (re-)changed again.

**Comment by lpgagnon** [comment]
the fact that it gets it "right" in 2 spots and wrong in 1 spot doesn't seem to agree with that explanation...

**Comment by NathanKell** [comment]
* The spots it gets it right are reporting the config, bare, I believe, not "the config as applied to the engine"
* When KSP compiles parts, it runs OnLoad. The first OnLoad will load the default config. That then becomes the prefab of the part. When KSP loads a craft file, it instantiates all parts from prefabs and then loads any data from the craft file. So that's no different from you spawning a part and changing its config yourself.
